spring.application.name=backend
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/ecommerce_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME:dpfpd7inr}
cloudinary.api-key=${CLOUDINARY_API_KEY:447781234546491}
cloudinary.api-secret=${CLOUDINARY_API_SECRET:TjhwLGyB1GI9-MveLS8DhuVkYOQ}

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
server.tomcat.max-http-form-post-size=-1
server.tomcat.max-swallow-size=-1
server.tomcat.max-parameter-count=10000
server.tomcat.max-part-count=1000

razorpay.key-id=${RAZORPAY_KEY_ID:rzp_test_SRQE8bn3JsSLIl}
razorpay.key-secret=${RAZORPAY_KEY_SECRET:OdZx4L8mdVzWxDW6HPxjNQi5}

app.cors.allowed-origins=${APP_CORS_ALLOWED_ORIGINS:http://localhost:3000,http://127.0.0.1:3000,https://*.vercel.app}

server.port=${PORT:8080}
server.address=0.0.0.0
spring.jpa.open-in-view=false

logging.file.name=app.log
logging.level.org.springframework.security=DEBUG
logging.level.com.ecommerce.backend=DEBUG
